FROM centos

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum install --allowerasing -y coreutils 

COPY fetch_logs.sh /
CMD  ["stdbuf", "-o0", "/fetch_logs.sh"]

